sudo: required

jobs:
  include:
    - language: scala
      scala:
        - 2.11.12
      os:
        - linux
      jdk:
        - openjdk8
      env:
        global:
          JAVA_OPTS=-Xmx4g
      cache:
        directories:
          - $HOME/.spark_nlp.dep.cache
          - $HOME/.m2
      before_install:
        - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
        - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install sbt; fi
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test
    - language: python
      python: 3.6
      os:
        - linux
      before_install:
        - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
        - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install sbt; fi
        - apt-get install pip3
        - pip3 install pyspark==2.4.4 numpy
        - export PYSPARK_PYTHON=python3.6
        - export PYSPARK_DRIVER_PYTHON=python3.6
        - sbt assemblyAndCopy
        - cd python; python3 run-tests.py;