sudo: required

os:
  - linux
  - osx

jobs:
  include:
    - stage: test-2.4
      name: "Test Apache Spark 2.4.x"
      language: scala
      scala:
        - 2.11.12
      jdk:
        - openjdk8
      addons:
        apt:
          packages:
            - pip
      env:
        global:
          JAVA_OPTS=-Xmx4g
      cache:
        directories:
          - $HOME/.spark_nlp.dep.cache
          - $HOME/.m2
      before_install:
        - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
        - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install sbt; fi
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test
