sudo: required

cache:
  directories:
    - $HOME/.spark_nlp.dep.cache

jobs:
  include:
    - stage: test
      name: "Test Apache Spark 2.4.x"
      language: scala
      scala:
        - '2.11.12'
      env:
        - DEFAULT_INTERFACE=eth0 # needed to setup django context
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test

