package:
  name: "spark-nlp"
  version: 3.4.4

app:
  entry: spark-nlp
  summary: Natural Language Understanding Library for Apache Spark.

source:
    fn: spark-nlp-3.4.4.tar.gz
    url: https://files.pythonhosted.org/packages/ea/8a/d333717eb304b721dc588e8f53ce18fb93da19b7abc50cc75083ca014d88/spark-nlp-3.4.4.tar.gz
    sha256: c4f02170ec45a9589d19ef5788342057bdf1f0db15a7e39adc3e2469fcd6d5c0
build:
  noarch: generic
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/JohnSnowLabs/spark-nlp/
  license: Apache License 2.0
  license_family: APACHE
  license_url: https://github.com/JohnSnowLabs/spark-nlp/blob/master/LICENSE
  description: John Snow Labs Spark-NLP is a natural language processing library built on top of Apache Spark ML. It provides simple, performant & accurate NLP annotations for machine learning pipelines, that scale easily in a distributed environment.
  summary: Natural Language Understanding Library for Apache Spark.
