package:
  name: "spark-nlp"
  version: 3.4.1

app:
  entry: spark-nlp
  summary: Natural Language Understanding Library for Apache Spark.

source:
    fn: spark-nlp-3.4.1.tar.gz
    url: https://files.pythonhosted.org/packages/1c/70/83dd4bedae58293b06c91e9248fc7060f67113d3272593eb29b0a8f713a3/spark-nlp-3.4.1.tar.gz
    sha256: 435547a5f6e12e62466c9829854b5a7d7a93b2a1858fb8498ce8a1903b4cd9ff
build:
  noarch: generic
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/JohnSnowLabs/spark-nlp/
  license: Apache License 2.0
  license_family: APACHE
  license_url: https://github.com/JohnSnowLabs/spark-nlp/blob/master/LICENSE
  description: John Snow Labs Spark-NLP is a natural language processing library built on top of Apache Spark ML. It provides simple, performant & accurate NLP annotations for machine learning pipelines, that scale easily in a distributed environment.
  summary: Natural Language Understanding Library for Apache Spark.
