package:
  name: "spark-nlp"
  version: 3.3.0

app:
  entry: spark-nlp
  summary: Natural Language Understanding Library for Apache Spark.

source:
    fn: spark-nlp-3.3.0.tar.gz
    url: https://files.pythonhosted.org/packages/af/65/af226c103f192683e3dff212f2d0c1f29cc2614ba1e88e24aed81cba475f/spark-nlp-3.3.0.tar.gz
    sha256: 5dad6b7d59ba01478520619d9a7e0eca20bd9bb6c80a438e8893df98d5ee6e7b
build:
  noarch: generic
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/JohnSnowLabs/spark-nlp/
  license: Apache License 2.0
  license_family: APACHE
  license_url: https://github.com/JohnSnowLabs/spark-nlp/blob/master/LICENSE
  description: John Snow Labs Spark-NLP is a natural language processing library built on top of Apache Spark ML. It provides simple, performant & accurate NLP annotations for machine learning pipelines, that scale easily in a distributed environment.
  summary: Natural Language Understanding Library for Apache Spark.
