name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip travis')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        scala: [2.11.12]
        java: [1.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Clean
      run: sbt clean
    - name: Run test
      run: sbt ++${{ matrix.scala }} test